#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'mcp-result.txt');
const outSqlPath = path.join(__dirname, 'rename-columns.sql');

function toSnakeCase(s) {
  return s
    .trim()
    .replace(/\s+/g, '_')         // spaces -> underscore
    .replace(/[^A-Za-z0-9_]/g, '') // remove other non-word chars
    .replace(/__+/g, '_')          // collapse repeated underscores
    .toLowerCase();
}

try {
  const raw = fs.readFileSync(filePath, 'utf8');
  const data = JSON.parse(raw);

  const statements = [];
  const issues = [];

  const tables = Array.isArray(data.tables) ? data.tables : [];
  for (const t of tables) {
    if (t.rls_enabled) {
      issues.push(`Table ${t.name} has RLS enabled — verify RLS policies are present and correct.`);
    }
    if (Array.isArray(t.columns)) {
      for (const col of t.columns) {
        if (/\s/.test(col) || /[^A-Za-z0-9_]/.test(col)) {
          const suggested = toSnakeCase(col);
          statements.push(`ALTER TABLE ${t.name} RENAME COLUMN "${col}" TO ${suggested};`);
          issues.push(`Column "${col}" in ${t.name} should be renamed to ${suggested}`);
        }
      }
    }
  }

  let outContent = `-- Generated by agent-test/check-mcp.js on ${new Date().toISOString()}\n` +
    `-- Review these ALTER statements before running them on your database.\n\n`;

  if (statements.length === 0) {
    outContent += '-- No columns with spaces or invalid characters were detected.\n';
  } else {
    outContent += statements.join('\n') + '\n';
  }

  fs.writeFileSync(outSqlPath, outContent, 'utf8');

  console.log(`Checked ${tables.length} table(s).`);
  console.log(`Issues found: ${issues.length}`);
  for (const i of issues) console.log('- ' + i);
  console.log('\nSQL written to: ' + outSqlPath);
  process.exit(0);
} catch (err) {
  console.error('Error:', err.message);
  process.exit(2);
}
