-- Generated by agent-test/check-mcp.js on 2026-03-16T17:45:04.687Z
-- Review these ALTER statements before running them on your database.

ALTER TABLE public.test RENAME COLUMN "ime i prezime" TO ime_i_prezime;
