/**
 * Environment secrets management.
 * Stores user-defined env vars (API keys, tokens, etc.) in localStorage.
 * Auto-injects them as a .env file in WebContainers when projects load.
 */

const STORAGE_KEY = 'vajb_env_secrets'

export interface Secret {
  key: string
  value: string
}

export function loadSecrets(): Secret[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw)
    if (!Array.isArray(parsed)) return []
    return parsed.filter(s => s && typeof s.key === 'string' && typeof s.value === 'string')
  } catch {
    return []
  }
}

export function saveSecrets(secrets: Secret[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(secrets))
  } catch (err) {
    console.warn('[Secrets] Save failed:', err)
  }
}

export function addSecret(key: string, value: string): Secret[] {
  const trimmedKey = key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, '_')
  if (!trimmedKey) return loadSecrets()
  const secrets = loadSecrets().filter(s => s.key !== trimmedKey)
  secrets.push({ key: trimmedKey, value: value.trim() })
  saveSecrets(secrets)
  return secrets
}

export function removeSecret(key: string): Secret[] {
  const secrets = loadSecrets().filter(s => s.key !== key)
  saveSecrets(secrets)
  return secrets
}

/** Build a .env file content from all stored secrets */
export function buildEnvFile(): string {
  const secrets = loadSecrets()
  if (secrets.length === 0) return ''
  const lines: string[] = ['# Auto-generated by VajbAgent']
  for (const s of secrets) {
    // Escape quotes and newlines in value
    const escaped = s.value.replace(/"/g, '\\"').replace(/\n/g, '\\n')
    lines.push(`${s.key}="${escaped}"`)
  }
  return lines.join('\n') + '\n'
}

/** Get a summary list of secret keys (for system prompt context) */
export function getSecretKeys(): string[] {
  return loadSecrets().map(s => s.key)
}
